### ISSUE TITLE
New Map: "Peta Dasar Manajemen Kebakaran"

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#24]
A new map, namely `Peta Dasar Manajemen Kebakaran`, within a new category: `Peta Dasar`. The map is a collection overlays from different map:

- Analisis Risiko Kebakaran
- hydrant kering
- hydrant reguler
- peta jalan
- peta relawan

The map comes with an interactive overlay menu, in which the user can change what sorts of map to be displayed.

Here is a nice example from [Leaflet docs](https://leafletjs.com/examples/layers-control/). Please see if we can use the following example.

**Comment by ahmadzakiakmal** [comment]
The new Map has been integrated and set as the default page on the dashboard. However, there are some known performance issues most likely due to the amount of GeoJSON Objects rendered on the map. There are delays when interacting with the overlay menu, as well as during the process of showing or hiding layers on the map.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/19cd0488-b088-4f66-94cf-0a9fe5129399)

**Comment by gtrdp** [comment]
Thanks. The performance issue does not seem to be that bad on my end. Seems like it depends on the PC spec. Let us assume that Damkar Jogja has a powerful machine.

Closing the issue.
